"""
Django settings for garantias project.

Generated by 'django-admin startproject' using Django 4.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
import sys
from pathlib import Path
from django.core.exceptions import ImproperlyConfigured
from manage import get_secret


# Este é o diretório do arquivo atual, que é o diretório base do projeto
BASE_DIR = Path(__file__).resolve().parent.parent.parent
# Este é o diretório que contém todos os aplicativos do projeto
APPS_DIR = os.path.join(BASE_DIR, "apps")
# Este é o diretório que contém todas as bibliotecas e aplicativos externos
EXTERNAL_BASE = os.path.join(BASE_DIR, "externals")
# Este é o diretório que contém todas as bibliotecas externas
EXTERNAL_LIBS_PATH = os.path.join(EXTERNAL_BASE, "libs")
# Este é o diretório que contém todos os aplicativos externos
EXTERNAL_APPS_PATH = os.path.join(EXTERNAL_BASE, "apps")

# Adicione todas as bibliotecas e aplicativos externos ao caminho
sys.path = [APPS_DIR, EXTERNAL_LIBS_PATH, EXTERNAL_APPS_PATH] + sys.path


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

SECRET_KEY = get_secret("DJANGO_SECRET_KEY")

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "apps.warranty",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

# Caminho para o arquivo de rotas
ROOT_URLCONF = "garantias.urls"

# Caminho para o arquivo de templates em DIRS
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, "garantias", "templates")],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "garantias.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Configurações de localização
LOCALE_PATHS = [os.path.join(BASE_DIR, "locale")]

# Configurações de arquivos estáticos
STATICFILES_DIRS = [os.path.join(BASE_DIR, "garantias", "static")]

STATIC_ROOT = os.path.join(BASE_DIR, "static")

# Configurações de arquivos de mídia
MEDIA_ROOT = os.path.join(BASE_DIR, "media")
